# Generated by Django 4.0.2 on 2022-02-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
    ]
