# Generated by Django 4.0.2 on 2022-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkIn',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkOut',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mop',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_category',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
